package Telas;

import javax.swing.JOptionPane;
import DAO.DAOUsuarios;
import Back.Usuario;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Montilha
 */
public class TelaInicial extends javax.swing.JFrame {
    
    DAOUsuarios dao = new DAOUsuarios();
    List<String> listaConsulta = new ArrayList<>();
    String aux = "";
    Usuario use = new Usuario();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        dao.CriaConexao();
    }
    
    private void abrirTelaDoUsuario() {
        TelaDoUsuario telaDoUsuario = new TelaDoUsuario(use);
        telaDoUsuario.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lb_menu = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        pf_senha = new javax.swing.JPasswordField();
        bt_cadastrar = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_menu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_menu.setText("MENU INICIAL");

        lb_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_email.setText("Email:");

        lb_senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_senha.setText("Senha:");

        pf_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_senhaActionPerformed(evt);
            }
        });

        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cadastrarMouseClicked(evt);
            }
        });

        bt_login.setText("Login");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lb_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_senha)
                            .addComponent(lb_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_email)
                            .addComponent(pf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(bt_cadastrar)
                        .addGap(96, 96, 96)
                        .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_menu)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senha)
                    .addComponent(pf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrar)
                    .addComponent(bt_login))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastrarMouseClicked
        if(!tf_email.getText().equals(null) && tf_email.getText().length() >= 10){
            if(!pf_senha.getText().equals(null) && pf_senha.getText().length() >= 8){
                use.setSenha(pf_senha.getText());
                use.setEmail(tf_email.getText());
                if (dao.Inserir(use)) {
                    use.setEmail(tf_email.getText());
                    use.setSenha(pf_senha.getText());
                    tf_email.setText("");
                    pf_senha.setText("");
                    
                    dao.Consultar(listaConsulta, use);
                    for(String dado : listaConsulta){
                        String[] elementos = dado.split(" - ");
                        use.setIdUsuario(Integer.parseInt(elementos[0]));
                    }
                    abrirTelaDoUsuario();

                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuario.");
                }
            } else{
                JOptionPane.showMessageDialog(this, "Senha muito curta");
            }
            use.setEmail(tf_email.getText());
        } else{
            JOptionPane.showMessageDialog(this, "Email muito curto");
        }
    }//GEN-LAST:event_bt_cadastrarMouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        use.setEmail(tf_email.getText());
        use.setSenha(pf_senha.getText());
        dao.Consultar(listaConsulta, use);
        if(!listaConsulta.isEmpty()){
            tf_email.setText("");
            pf_senha.setText("");
            
            dao.Consultar(listaConsulta, use);
            for(String dado : listaConsulta){
                String[] elementos = dado.split(" - ");
                use.setIdUsuario(Integer.parseInt(elementos[0]));
            }
            abrirTelaDoUsuario();
        } else{
            JOptionPane.showMessageDialog(this, "Email ou senha incorreto");
        }
    }//GEN-LAST:event_bt_loginMouseClicked

    private void pf_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_login;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_menu;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JPasswordField pf_senha;
    private javax.swing.JTextField tf_email;
    // End of variables declaration//GEN-END:variables
}
