# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  # Defina as vari치veis necess치rias, como chaves de API, URLs, etc.

before_script:
  # Comandos executados antes de cada job

build:
  stage: build
  script:
    - echo "Construindo o c칩digo..."

test:
  stage: test
  script:
    - echo "Executando testes..."

deploy:
  stage: deploy
  script:
    - echo "Implantando o c칩digo..."
